import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import AppProvider from "@/provider/AppProvider";
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from "sonner";

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Wholeheart Campaigns | Website",
  description: "Generated by create Wholeheart",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${notoSerif.className} antialiased`}>
        <NextTopLoader color="#0070f3" height={3} showSpinner={false} />
        <AppProvider>
          <AuthProvider>
            <div>{children}</div>
            <Toaster richColors position="bottom-right" />
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}